---
- name: Dependencies | Ensure packages for installing and using Java installed
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - python-pycurl
    - ant
    - maven

- name: Install Oracle Java 8 Repo Installer Repository
  apt_repository: repo=ppa:webupd8team/java update-cache=yes 
  when: oracle_java_version == 8
  sudo: yes

- name: Install Oracle Java 10 Repo Installer Repository
  apt_repository: repo=ppa:linuxuprising/java
  when: oracle_java_version == 10
  sudo: yes

- name: Wizardry to bypass the Oracle License File prompt
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  sudo: yes

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java-8-installer
    - ca-certificates
    - oracle-java-set-default
  when: oracle_java_version == 8
  sudo: yes

- name: Install Oracle Java 10
  apt: pkg=oracle-java10-installer
  when: oracle_java_version == 10
  sudo: yes
