---

- name: Ensure ansible-cache directory exists
  shell: mkdir /var/local/ansible-cache creates=/var/local/ansible-cache
  sudo: yes

- name: Ensure directory for EMR CLI tools exists in /vagrant/emr-cli
  shell: mkdir /vagrant/emr-cli creates=/vagrant/emr-cli

- name: Download EMR CLI 
  get_url: dest=/var/local/ansible-cache url=http://elasticmapreduce.s3.amazonaws.com/elastic-mapreduce-ruby.zip
  sudo: yes

- name: Ensure EMR CLI is extracted
  shell: chdir=/var/local/ansible-cache unzip elastic-mapreduce-ruby.zip -d /vagrant creates=/vagrant/elastic-mapreduce-ruby

- name: Print a useful message
  debug: msg="EMR CLI tools installed into /vagrant/elastic-mapreduce-ruby. Remember to execute 'rvm use 1.8.7' before running them..."