---
- name: Install dependencies required to setup a new version of Python
  sudo: yes
  apt: pkg={{ item }} state=latest
  tags: [packages]
  with_items:
    - build-essential
    - libsqlite3-dev
    - sqlite3 # for the command line client
    - libxml2-dev
    - bzip2
    - libbz2-dev
    - libssl-dev
    - redis-server

- name: Ensure ansible-cache directory exists
  shell: mkdir /var/local/ansible-cache creates=/var/local/ansible-cache
  sudo: yes

# Install Python 3.5
- name: Download Python 3.5
  get_url: dest=/var/local/ansible-cache url=https://www.python.org/ftp/python/3.5.4/Python-3.5.4.tar.xz
  sudo: yes

- name: Ensure Python 3.5 is extracted
  shell: chdir=/var/local/ansible-cache tar xJf ./Python-3.5.4.tar.xz -C /opt creates=/opt/Python-3.5.4
  sudo: yes

- name: Ensure Python 3.5 is configured
  shell: chdir=/opt/Python-3.5.4 ./configure --prefix=/opt/python3.5

- name: Ensure Python 3.5 make'd
  shell: chdir=/opt/Python-3.5.4 make

- name: Ensure Python 3.5 installed
  shell: chdir=/opt/Python-3.5.4 make install  # Need to add a 'creates=' flag here
  sudo: yes

# Install Python 2.7
- name: Download Python 2.7
  get_url: dest=/var/local/ansible-cache url=http://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz 
  sudo: yes

- name: Ensure Python 2.7 is extracted
  shell: chdir=/var/local/ansible-cache tar xJf ./Python-2.7.6.tar.xz -C /opt creates=/opt/Python-2.7.6
  sudo: yes

- name: Ensure Python 2.7 is configured
  shell: chdir=/opt/Python-2.7.6 ./configure --prefix=/opt/python2.7

- name: Ensure Python 2.7 make'd
  shell: chdir=/opt/Python-2.7.6 make

- name: Ensure Python 2.7 installed
  shell: chdir=/opt/Python-2.7.6 make install  # Need to add a 'creates=' flag here
  sudo: yes

# Now download the Snowplow Python Tracker from Git
- name: Add Github to the list of known hosts so that we can clone the repo via SSH
  shell: ssh-keyscan -H github.com >> /home/vagrant/.ssh/known_hosts 
  sudo: yes

# Setup a Python 3.5 virtual environment to run the tracker
- name: Setup an environment for the tracker using Python 3.5
  shell: virtualenv -p /opt/python3.5/bin/python3.5 ~/snowplow-python-3.5-tracker-environment

- name: Install packages required for the Python Tracker in the Python 3.5 environment
  pip: name={{ item }} virtualenv="~/snowplow-python-3.5-tracker-environment"
  with_items: 
    - python-dateutil
    - httmock
    - freezegun
    - pytest

- name: Install the packages specified in requirements.txt in the Python 3.5 environment
  pip: requirements=/vagrant/requirements-test.txt virtualenv=~/snowplow-python-3.5-tracker-environment

# Setup a Python 2.7 virtual environment to run the tracker
- name: Setup an environment for the tracker using Python 2.7
  shell: virtualenv -p /opt/python2.7/bin/python2.7 ~/snowplow-python-2.7-tracker-environment

- name: Install packages required for the Python Tracker in the Python 2.7 environment 
  pip: name={{ item }} virtualenv="~/snowplow-python-2.7-tracker-environment"
  with_items: 
    - python-dateutil
    - httmock
    - freezegun
    - pytest

- name: Install the packages specified in requirements.txt in the Python 2.7 environment
  pip: requirements=/vagrant/requirements-test.txt virtualenv=~/snowplow-python-2.7-tracker-environment
